coop:
  channel: sandbox
  ccid: ssm
  user:
    name: dfef919ef60296ca173d99f2132becde
    password: 660bd560b383333750f629362e0160f9
    org: bclan
  endorsers: peer0:bclan
  config:
    file: file:../network-it/config.json
    crypto: file:../network-it/

server:
  port : 9090
