# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2019
# License: Apache-2.0

version: '2'

networks:
  bc1net:

services:
  ca.pr-bc1.chain-ops.net:
    container_name: ca_ChainOpsBC1Peer
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.pr-bc1.chain-ops.net-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${ca__CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/tlsca/tlsca.pr-bc1.chain-ops.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/tlsca/${ca__TLS_KEYFILE}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ${ca__ADMIN}:${ca__PASSWD} -d'
    volumes:
      - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/ca/:/etc/hyperledger/ca/
      - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/tlsca/:/etc/hyperledger/tlsca/
    networks:
      - bc1net

  ca.pr-bc1.civis-blockchain.org:
    container_name: ca_CivisBlockchainBC1Peer
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.pr-bc1.civis-blockchain.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${ca__CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/tlsca/tlsca.pr-bc1.civis-blockchain.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/tlsca/${ca__TLS_KEYFILE}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ${ca__ADMIN}:${ca__PASSWD} -d'
    volumes:
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/ca/:/etc/hyperledger/ca/
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/tlsca/:/etc/hyperledger/tlsca/
    networks:
      - bc1net

  ca.pr-bc1.thingagora.org:
    container_name: ca_ThingagoraBC1Peer
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.pr-bc1.thingagora.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${ca__CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/tlsca/tlsca.pr-bc1.thingagora.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/tlsca/${ca__TLS_KEYFILE}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ${ca__ADMIN}:${ca__PASSWD} -d'
    volumes:
      - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/ca/:/etc/hyperledger/ca/
      - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/tlsca/:/etc/hyperledger/tlsca/
    networks:
      - bc1net

  orderer0.or-bc1.chain-ops.net:
    container_name: orderer0_ChainOpsBC1Orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ChainOpsBC1OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/config
        - ./crypto-config/ordererOrganizations/or-bc1.chain-ops.net/orderers/orderer0.or-bc1.chain-ops.net/msp/:/etc/hyperledger/msp
        - ./crypto-config/ordererOrganizations/or-bc1.chain-ops.net/orderers/orderer0.or-bc1.chain-ops.net/tls/:/etc/hyperledger/tls
    networks:
      - bc1net

  peer0.pr-bc1.chain-ops.net:
    container_name: peer0_ChainOpsBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer0.pr-bc1.chain-ops.net
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ChainOpsBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer0.pr-bc1.chain-ops.net:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/peers/peer0.pr-bc1.chain-ops.net/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/peers/peer0.pr-bc1.chain-ops.net/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  peer1.pr-bc1.chain-ops.net:
    container_name: peer1_ChainOpsBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer1.pr-bc1.chain-ops.net
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ChainOpsBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer1.pr-bc1.chain-ops.net:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/peers/peer1.pr-bc1.chain-ops.net/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.chain-ops.net/peers/peer1.pr-bc1.chain-ops.net/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  peer0.pr-bc1.civis-blockchain.org:
    container_name: peer0_CivisBlockchainBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer0.pr-bc1.civis-blockchain.org
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=CivisBlockchainBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer0.pr-bc1.civis-blockchain.org:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pr-bc1.civis-blockchain.org:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer0.pr-bc1.civis-blockchain.org/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer0.pr-bc1.civis-blockchain.org/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  peer1.pr-bc1.civis-blockchain.org:
    container_name: peer1_CivisBlockchainBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer1.pr-bc1.civis-blockchain.org
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=CivisBlockchainBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer1.pr-bc1.civis-blockchain.org:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pr-bc1.civis-blockchain.org:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer1.pr-bc1.civis-blockchain.org/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer1.pr-bc1.civis-blockchain.org/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  peer0.pr-bc1.thingagora.org:
    container_name: peer0_ThingagoraBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer0.pr-bc1.thingagora.org
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ThingagoraBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer0.pr-bc1.thingagora.org:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/peers/peer0.pr-bc1.thingagora.org/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/peers/peer0.pr-bc1.thingagora.org/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  peer1.pr-bc1.thingagora.org:
    container_name: peer1_ThingagoraBC1Peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bc1net
      - CORE_PEER_ID=peer1.pr-bc1.thingagora.org
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ThingagoraBC1PeerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=peer1.pr-bc1.thingagora.org:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/peers/peer1.pr-bc1.thingagora.org/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/pr-bc1.thingagora.org/peers/peer1.pr-bc1.thingagora.org/tls:/etc/hyperledger/tls/
    networks:
      - bc1net

  cli.or-bc1.chain-ops.net:
    container_name: cli-ChainOpsBC1Orderer
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli.${cli_ORGA}
      - CORE_PEER_ADDRESS=peer0.${cli_ORGA}:7051
      - CORE_PEER_LOCALMSPID=${cli_MSP}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/user/msp/
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/user/tls/client.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/user/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/user/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/blockchain-coop/
        - ./../util/:/opt/blockchain-coop/
        - ./crypto-config/peerOrganizations/${cli_ORGA}/users/${cli_USER}@${cli_ORGA}/:/etc/hyperledger/user/
        - ./crypto-config/ordererOrganizations/or-bc1.chain-ops.net/tlsca/:/etc/hyperledger/orderer/
        - ./config/:/etc/hyperledger/config/
    networks:
        - bc1net

  explorerdb.pr-bc1.civis-blockchain.org:
    image: hyperledger/explorer-db:0.3.9.1
    container_name: explorerdb.pr-bc1.civis-blockchain.org
    hostname: explorerdb.pr-bc1.civis-blockchain.org
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=${explorerdb__ADMIN}
      - DATABASE_PASSWORD=${explorerdb__PASSWD}
    ports:
      - 5432:5432
    volumes:
      - ./explorer-config/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
    networks:
      - bc1net

  explorer.pr-bc1.civis-blockchain.org:
    image: civisblockchain/explorer:0.1.0
    container_name: explorer.pr-bc1.civis-blockchain.org
    hostname: explorer.pr-bc1.civis-blockchain.org
    environment:
      - DATABASE_HOST=explorerdb.pr-bc1.civis-blockchain.org
      - DATABASE_USERNAME=${explorerdb__ADMIN}
      - DATABASE_PASSWD=${explorerdb__PASSWD}
      - DISCOVERY_AS_LOCALHOST=false
      - ADMIN_USERNAME=
      - ADMIN_SECRET=
    volumes:
      - ./explorer-config/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/users/User1@pr-bc1.civis-blockchain.org:/etc/hyperledger/pr-bc1.civis-blockchain.org/user
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer0.pr-bc1.civis-blockchain.org:/etc/hyperledger/pr-bc1.civis-blockchain.org/peer0
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/peers/peer1.pr-bc1.civis-blockchain.org:/etc/hyperledger/pr-bc1.civis-blockchain.org/peer1
      - ./crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/ca:/etc/hyperledger/pr-bc1.civis-blockchain.org/ca
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8080:8080
    networks:
        - bc1net

  coop-rest-java.pr-bc1.civis-blockchain.org:
    image: civisblockchain/coop-rest
    container_name: coop-rest-java.pr-bc1.civis-blockchain.org
    hostname: coop-rest-java.pr-bc1.civis-blockchain.org
    environment:
      - coop_channel=sandbox
      - coop_ccid=ssm
      - coop_user_name=${ca__ADMIN}
      - coop_user_password=${ca__PASSWD}
      - coop_user_org=CivisBlockchain
      - coop_config_file=file:/opt/rest-coop/config.json
      - coop_config_crypto=file:/opt/rest-coop
      - coop_endorsers=peer0:CivisBlockchain,peer1:CivisBlockchain
    volumes:
      - ./config.json:/opt/rest-coop/config.json
      - ./crypto-config:/opt/rest-coop/crypto-config
    ports:
      - 9090:9090
    networks:
      - bc1net